org: ithapadeepak
app: aws-node-express-api-project
service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
 - serverless-offline
    
custom:
  serverless-offline:
    httpsProtocol: "cert"
    host: "dev-api-local.ideepakthapa.com"
    
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
